title: Arc
email: vin@misday.com
description: ""
baseurl: ""
url: ""

# Build settings

## For gitbook theme
remote_theme: sighingnow/jekyll-gitbook
plugins:
- jekyll-remote-theme
syntax_highlighter_style: colorful
toc:
  enabled: true
  h_min: 1
  h_max: 3
tracker:
  google_analytics: "UA-28333273-1"
